# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run benchmark and update gist

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.sln'

jobs:
  benchmark:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Clean Benchmark
      run: dotnet clean Benchmark/Benchmark.csproj -c Release
      
    - name: Build Benchmark
      run: dotnet build Benchmark/Benchmark.csproj -c Release /p:CheckCacheMisses=true
      
    - name: Run Benchmark
      run: dotnet run --project Benchmark/Benchmark.csproj -c Release --no-build
      
    - name: Update Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.TOKEN }}
        gist_id: 6d254a684cf580441bf58690ad9485c3
        file_path: report.md
