name: Test

on:
  push:
    branches: ["main"]
    paths:
      - './github/workflows/benchmark.yml'
      - './github/workflows/test.yml'
      - '**.cs'
      - '**.csproj'
      - '**.sln'
  pull_request:
    branches: ["main"]
    paths:
      - './github/workflows/benchmark.yml'
      - './github/workflows/test.yml'
      - '**.cs'
      - '**.csproj'
      - '**.sln'
  merge_group:
    branches: ["main"]
    paths:
      - './github/workflows/benchmark.yml'
      - './github/workflows/test.yml'
      - '**.cs'
      - '**.csproj'
      - '**.sln'
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  CONFIGURATION: 'Release'
  CHECK_CACHE_MISSES: 'false'
  TEST_LOGGER: 'console;verbosity=normal'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.out.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore Benchmark
        run: dotnet restore
      - name: Build Benchmark
        run: dotnet build -c ${{ env.CONFIGURATION }} /p:CheckCacheMisses=${{ env.CHECK_CACHE_MISSES }}
      - name: Run Tests
        run: dotnet test -c ${{ env.CONFIGURATION }} -v quiet --nologo -l:"${{ env.TEST_LOGGER }}"
